# Generated by Django 4.0.6 on 2022-08-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceplan',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='priceplan',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
