# Generated by Django 4.0.6 on 2022-08-15 06:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advice',
            options={'verbose_name': 'توصیه ها', 'verbose_name_plural': 'توصیه ها'},
        ),
        migrations.AlterModelOptions(
            name='call',
            options={'verbose_name': 'اطلاعات تماس', 'verbose_name_plural': 'اطلاعات تماس'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی'},
        ),
        migrations.AlterModelOptions(
            name='head',
            options={'verbose_name': 'قسمت بالایی', 'verbose_name_plural': 'قسمت بالایی'},
        ),
        migrations.AlterModelOptions(
            name='historyleft',
            options={'verbose_name': 'تاریچه سمت چپ', 'verbose_name_plural': 'تاریچه سمت چپ'},
        ),
        migrations.AlterModelOptions(
            name='historyright',
            options={'verbose_name': 'تاریچه سمت راست', 'verbose_name_plural': 'تاریچه سمت راست'},
        ),
        migrations.AlterModelOptions(
            name='khadamat',
            options={'verbose_name': 'خدمات', 'verbose_name_plural': 'خدمات'},
        ),
        migrations.AlterModelOptions(
            name='priceplan',
            options={'verbose_name': 'برنامه های قیمت', 'verbose_name_plural': 'برنامه های قیمت'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'آثار', 'verbose_name_plural': 'آثار'},
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'تنظیمات سایت', 'verbose_name_plural': 'تنظیمات سایت'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'تگ ها', 'verbose_name_plural': 'تگ ها'},
        ),
        migrations.AlterModelOptions(
            name='zirhead',
            options={'verbose_name': ' زیر قسمت بالایی', 'verbose_name_plural': 'زیر قسمت بالایی'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='categry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='advice',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='advice',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='advice',
            name='star',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='تعداد ستاره ها'),
        ),
        migrations.AlterField(
            model_name='advice',
            name='text',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='call',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='call',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کشور'),
        ),
        migrations.AlterField(
            model_name='call',
            name='daftar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='دفتر'),
        ),
        migrations.AlterField(
            model_name='call',
            name='poshtebany',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='پشتیبانی'),
        ),
        migrations.AlterField(
            model_name='call',
            name='post',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='call',
            name='shakhsy',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تلفن شخصی'),
        ),
        migrations.AlterField(
            model_name='call',
            name='skyp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسکایپ'),
        ),
        migrations.AlterField(
            model_name='call',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='خیابان'),
        ),
        migrations.AlterField(
            model_name='call',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تلگرام'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='head',
            name='alt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیحات عکس'),
        ),
        migrations.AlterField(
            model_name='head',
            name='image',
            field=models.ImageField(upload_to='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='head',
            name='matn_moteghayer1',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='متن متغیر۱'),
        ),
        migrations.AlterField(
            model_name='head',
            name='matn_moteghayer2',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='متن متغیر۲'),
        ),
        migrations.AlterField(
            model_name='head',
            name='matn_moteghayer3',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='متن متغیر۳'),
        ),
        migrations.AlterField(
            model_name='head',
            name='matn_moteghayer4',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='متن متغیر۴'),
        ),
        migrations.AlterField(
            model_name='head',
            name='matn_samet',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='متن ثابت'),
        ),
        migrations.AlterField(
            model_name='historyleft',
            name='index',
            field=models.PositiveIntegerField(verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='historyleft',
            name='text',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='historyleft',
            name='time',
            field=models.CharField(max_length=100, verbose_name='تایم'),
        ),
        migrations.AlterField(
            model_name='historyleft',
            name='title',
            field=models.CharField(max_length=100, verbose_name='تیتر'),
        ),
        migrations.AlterField(
            model_name='historyright',
            name='index',
            field=models.PositiveIntegerField(verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='historyright',
            name='text',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='historyright',
            name='time',
            field=models.CharField(max_length=100, verbose_name='تایم'),
        ),
        migrations.AlterField(
            model_name='historyright',
            name='title',
            field=models.CharField(max_length=100, verbose_name='تیتر'),
        ),
        migrations.AlterField(
            model_name='khadamat',
            name='text_tozih',
            field=models.CharField(max_length=500, verbose_name='متن توضیح'),
        ),
        migrations.AlterField(
            model_name='khadamat',
            name='title',
            field=models.CharField(max_length=100, verbose_name='تیتر'),
        ),
        migrations.AlterField(
            model_name='priceplan',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='priceplan',
            name='time',
            field=models.IntegerField(blank=True, null=True, verbose_name='زمان'),
        ),
        migrations.AlterField(
            model_name='priceplan',
            name='title',
            field=models.CharField(max_length=100, verbose_name='تیتر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100, verbose_name='تیتر'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='left',
            field=models.CharField(default='تاریخچه کار', max_length=100, verbose_name='چپ'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='right',
            field=models.CharField(default='تحصیلات', max_length=100, verbose_name='راست'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='tags',
            field=models.ManyToManyField(to='main.tag', verbose_name='تگها'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='text',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='tozihplan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='tozihplan',
            name='priceplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.priceplan', verbose_name='برنامه های قیمت'),
        ),
        migrations.AlterField(
            model_name='zirhead',
            name='is_more',
            field=models.BooleanField(verbose_name='بیشتر از ؟'),
        ),
        migrations.AlterField(
            model_name='zirhead',
            name='number',
            field=models.IntegerField(verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='zirhead',
            name='text_tozih',
            field=models.CharField(max_length=100, verbose_name='متن توضیح'),
        ),
    ]
