# Generated by Django 4.0.6 on 2022-08-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_advice_options_alter_call_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='alt',
            field=models.CharField(max_length=100, null=True, verbose_name='توضیحات عکس'),
        ),
        migrations.AddField(
            model_name='product',
            name='alt',
            field=models.CharField(max_length=100, null=True, verbose_name='توضیحات عکس'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='title_page',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='head',
            name='alt',
            field=models.CharField(max_length=100, null=True, verbose_name='توضیحات عکس'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='alt',
            field=models.CharField(max_length=100, null=True, verbose_name='توضیحات عکس'),
        ),
    ]
