# Generated by Django 4.0.6 on 2022-08-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_advice_alt_product_alt_sitesetting_title_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
