# Generated by Django 4.0.6 on 2022-08-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_sitesetting_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='head',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
