# Generated by Django 4.0.6 on 2022-08-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_skyp_call_skype'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='call',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='head',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
