# Generated by Django 4.0.4 on 2022-08-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_tozihplan_options_advice_owner_call_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='head',
            name='matn_moteghayer1',
        ),
        migrations.RemoveField(
            model_name='head',
            name='matn_moteghayer2',
        ),
        migrations.RemoveField(
            model_name='head',
            name='matn_moteghayer3',
        ),
        migrations.RemoveField(
            model_name='head',
            name='matn_moteghayer4',
        ),
        migrations.RemoveField(
            model_name='head',
            name='matn_samet',
        ),
        migrations.RemoveField(
            model_name='head',
            name='title',
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='text',
            field=models.TextField(verbose_name='توضیحات تگ هدر'),
        ),
    ]
