# Generated by Django 4.0.6 on 2022-08-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_profile_resume_alter_profile_link_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity',
            field=models.CharField(max_length=300, verbose_name='مهارت ها'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='name',
            field=models.CharField(max_length=300, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='number',
            field=models.IntegerField(verbose_name='درصد مهارت'),
        ),
        migrations.AlterField(
            model_name='detailprofile',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='detailprofile',
            name='value',
            field=models.CharField(max_length=100, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='line',
            name='name',
            field=models.CharField(max_length=300, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='line',
            name='number',
            field=models.IntegerField(verbose_name='درصد مهارت'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='info',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='link_resume',
            field=models.CharField(blank=True, max_length=300, verbose_name='ادرس رزومه'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='رزومه'),
        ),
    ]
