# Generated by Django 4.0.4 on 2022-08-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_alter_activity_owner_alter_circle_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='link_resume',
            field=models.URLField(blank=True, verbose_name='ادرس رزومه'),
        ),
    ]
